name: Generate documentation

on:
  workflow_dispatch:
    push:
     branches: [ master ]
     paths:
     - 'working_copy/eu-cm-ontology.owl'

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        sudo python -m pip install --upgrade pip
        sudo pip install ontospy[FULL]
    - name: Generate docs
      run: |
        sudo ontospy gendocs -o docs/summary --type 1 --nobrowser working_copy/eu-cm-ontology.owl
        sudo ontospy gendocs -o docs/browse --type 2 --nobrowser working_copy/eu-cm-ontology.owl
        sudo ontospy gendocs -o docs/classtree --type 4 --nobrowser working_copy/eu-cm-ontology.owl
        sudo ontospy gendocs -o docs/graph --type 10 --nobrowser working_copy/eu-cm-ontology.owl

    - name: Commit and push
      run: |
        sudo git config --global user.name 'Tim Hendriks'
        sudo git config --global user.email 't.hendriks@maastrichtuniversity.nl'
        sudo git commit -am "Automatically generate documentation from the CBCM OWL ontology file using Ontospy gendocs."
        sudo git push
