name: Generate documentation

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
    - 'working_copy/eu-cm-ontology.owl'
    - 'scripts/generate_ontologyterms_flatfile_and_tooltips.py'
    - 'docs/widoco.jar'

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ontospy
        pip install Django==1.10.3 Pygments==2.1.3
        mkdir -p docs/browse docs/tree docs/graph docs/lode
        wget -O docs/widoco.jar https://github.com/dgarijo/Widoco/releases/download/v1.4.15_1/widoco-1.4.15-jar-with-dependencies.jar
        pip install owlready2==0.26
    
    - name: Generate docs with Widoco (LODE)
      run: |
        java -jar docs/widoco.jar -ontFile working_copy/eu-cm-ontology.owl -outFolder docs/lode/ -getOntologyMetadata -oops -rewriteAll -webVowl

    - name: Generate docs with Ontospy
      run: |
        ontospy gendocs -o docs/summary --type 1 --nobrowser working_copy/eu-cm-ontology.owl
        ontospy gendocs -o docs/browse --preflabel label --type 2 --nobrowser working_copy/eu-cm-ontology.owl
        ontospy gendocs -o docs/classtree --type 4 --nobrowser working_copy/eu-cm-ontology.owl
        ontospy gendocs -o docs/graph --type 10 --nobrowser working_copy/eu-cm-ontology.owl

    - name: Generate ontology terms flatlist and tooltips for Hypothes.is integration
      run: |
        python scripts/generate_ontologyterms_flatfile_and_tooltips.py

    - name: Commit and push
      run: |
        git config --global user.name 'Kody Moodley'
        git config --global user.email 'kody.moodley@gmail.com'
        git add -A && git commit -m "Automatically generate ontology documentation using Widoco and Ontospy, as well as a flatfile list of ontology terms for tagging in text annotation platforms."
        git push
